routes/web.php
<?php

// public
use App\Http\Controllers\PublicController;

// user
use App\Http\Controllers\User\AuctionController as User_AuctionController;

// officer
use App\Http\Controllers\Officer\AuctionController as Officer_AuctionController;
use App\Http\Controllers\Officer\OfficerController as Officer_OfficerController;

// admin
use App\Http\Controllers\Admin\AuctionController as Admin_AuctionController;
use App\Http\Controllers\Admin\OfficerController as Admin_OfficerController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Public
// Route::get('/', function () {
//     return redirect(route('index-dcms'));
// });
Route::get('/', [PublicController::class, 'index'])->name('landing-page');
Route::get('/about', [PublicController::class, 'about'])->name('about');
Route::get('/auction', [PublicController::class, 'auction'])->name('auction');
Route::get('/contact', [PublicController::class, 'contact'])->name('contact');
Route::get('/term-of-use', [PublicController::class, 'term_of_use'])->name('term-of-use');
Route::get('/privacy-policy', [PublicController::class, 'privacy_policy'])->name('privacy-policy');

// Auth User
Auth::routes(['verify' => true]);

// OAuth Google
Route::get('/google', 'User\GoogleController@redirect');
Route::get('/callback', 'User\GoogleController@callback');

// Auth Officer
Route::name('officer.')->prefix('officer')->middleware('guest')->group(function () {
    Route::get('/login', 'Auth\OfficerLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\OfficerLoginController@login');
    Route::post('/logout', 'Auth\OfficerLoginController@logout')->name('logout');
});

// Officer
Route::name('officer.')->prefix('officer')->middleware('auth:officer', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'Officer\OfficerController@index')->name('dashboard');
    // Lelang
    Route::get('/auction-request', 'Officer\AuctionController@index')->name('auction-request');
    Route::get('/auction-request/{id}', 'Officer\AuctionController@show')->name('auction-request.detail');
    Route::patch('/auction-request/{id}', 'Officer\AuctionController@update')->name('auction-request.update');
    // Profile
    Route::get('/profile', 'Officer\OfficerController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Officer\OfficerController@profile_update');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth:officer', 'verified')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
    // Officer
    Route::resource('officers', 'Admin\OfficerController', ['names' => ['index' => 'officers']]);
    // User
    Route::resource('users', 'Admin\UserController', ['names' => ['index' => 'users']]);
    // Lelang
    Route::resource('auctions', 'Admin\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::get('/export/auctions', 'Admin\AuctionController@export')->name('export');
    // Profile
    Route::get('/profile', 'Admin\AdminController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Admin\AdminController@profile_update');
});

// User
// Route::get('/user', function () {
//     return redirect(route('user.dashboard'));
// });
Route::get('/user', 'User\UserController@index');

// User
Route::name('user.')->prefix('user')->middleware('auth', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'User\UserController@index')->name('dashboard');
    // Trashed
    Route::get('/trashed', 'User\UserController@trash')->name('trashed');
    Route::get('/restore/{id}', 'User\UserController@restore')->name('restore');
    // Profile
    Route::get('/profile', 'User\UserController@profile')->name('profile');
    Route::patch('/profile/{id}', 'User\UserController@profile_update');
    // Goodies
    Route::post('/dependent-dropdown/goodies/city', 'User\GoodsController@city')->name('goodies.city');
    Route::post('/dependent-dropdown/goodies/district', 'User\GoodsController@district')->name('goodies.district');
    Route::post('/dependent-dropdown/goodies/village', 'User\GoodsController@village')->name('goodies.village');
    Route::get('/goodies/export', 'User\GoodsController@export')->name('goodies.export');
    Route::post('/goodies/export-filter', 'User\GoodsController@export_filter')->name('goodies.export_filter');
    Route::resource('goodies', 'User\GoodsController', ['names' => ['index' => 'goodies']]);
    // Auctions
    Route::get('/auctions/export', 'User\AuctionController@export')->name('auctions.export');
    Route::post('/auctions/export-filter', 'User\AuctionController@export_filter')->name('auctions.export_filter');
    Route::get('/my-auctions', 'User\AuctionController@my_auction')->name('my-auctions');
    Route::get('/auctions/{id}/detail', 'User\AuctionController@auction_detail')->name('auction-detail');
    Route::post('/auctions/{id}/follow', 'User\AuctionController@auction_follow')->name('auction-follow');
    Route::resource('auctions', 'User\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::patch('/auctions/{id}/bid', 'User\AuctionController@bid')->name('auction-bid');
    // Auction Requirement
    Route::get('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card')->name('identity-card');
    Route::patch('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card_update');
    Route::post('/dependent-dropdown/city', 'AuctionRequirementController@city')->name('city');
    Route::post('/dependent-dropdown/district', 'AuctionRequirementController@district')->name('district');
    Route::post('/dependent-dropdown/village', 'AuctionRequirementController@village')->name('village');
    Route::get('/auction-requirement/npwp', 'AuctionRequirementController@npwp')->name('npwp');
    Route::get('/auction-requirement/bank-account', 'AuctionRequirementController@bank_account')->name('bank');
    // Auctions History
    Route::get('/auction-histories/export', 'User\AuctionHistoryController@export')->name('auction-histories.export');
    Route::post('/auction-histories/export-filter', 'User\AuctionHistoryController@export_filter')->name('auction-histories.export_filter');
    Route::resource('/auction-histories', 'User\AuctionHistoryController', ['names' => ['index' => 'auction-histories']]);
    Route::patch('/auction-histories/{id}', 'User\AuctionHistoryController@update')->name('bid');
});

// log viewer
Route::get('/log', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);

app/Auction.php
<?php

namespace App;

use App\User;
use App\Goods;
use App\Officer;
use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Auction extends Model
{
    use Uuid;
    use SoftDeletes;

    protected $guarded   = [];
    public $incrementing = false;

    public function goods()
    {
        return $this->belongsTo(Goods::class, 'goods_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function officer()
    {
        return $this->belongsTo(Officer::class, 'officer_id');
    }
}

app/Http/Controllers/Admin/AuctionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Auction;
use App\Goods;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class AuctionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $auctions = Auction::paginate(10);

        return view('admin.auctions.index', compact('auctions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $goodies = Goods::where('user_id', Auth::user()->id)->get();
        $goodies = Goods::whereNotIn('id', Auction::get('goods_id'))->get();

        return view('admin.auctions.create', [
            'goodies'  => $goodies
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'goods_id'    => 'required|numeric|unique:auctions',
            'start_date'  => 'required|date',
            'end_date'    => 'required|date',
            'user_id'     => 'numneric',
            'officer_id'  => 'numeric'
        ]);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $goodies = Goods::where('id', $data['goods_id'])->get();

        foreach ($goodies as $goods) {
            $initial_price = $goods->initial_price;
        }

        $data['final_price'] = str_replace("Rp. ", "", $initial_price);
        $data['user_id']     = Auth::user()->id;
        $data['officer_id']  = 1;
        $data['status']      = 'closed';

        Auction::create($data);

        return redirect(route('admin.auctions.create'))->with('status', 'Permohonan Lelang berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function show(Auction $auction)
    {
        $status = ['opened', 'closed'];

        return view('admin.auctions.show', [
            'model'  => $auction,
            'status' => $status
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function edit(Auction $auction)
    {
        dd($auction);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Auction $auction)
    {
        $request->validate([
            'start_date' => 'required|date',
            'end_date'   => 'required|date',
            'status'     => 'required'
        ]);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $auction->update($data);

        redirect('/admin/auction/' . $auction->id)->with('status', 'Lelang berhasil diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Auction $auction)
    {
        //
    }

    public function export()
    {
        $auctions = Auction::all();

        $pdf = PDF::loadview('admin.auctions.export', compact('auctions'))->setPaper('A4', 'potrait');
        return $pdf->stream('Laporan-lelang');
    }
}

app/Http/Controllers/Officer/AuctionController.php
<?php

namespace App\Http\Controllers\Officer;

use App\Auction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AuctionController extends Controller
{
    public function index()
    {
        $auctions = Auction::all();

        return view('officers.auctions.index', [
            'auctions' => $auctions
        ]);
    }

    public function show($id)
    {
        $auctions = Auction::where('id', $id)->first();
        $status   = ['process', 'opened', 'closed'];

        return view('officers.auctions.show', [
            'model' => $auctions,
            'status' => $status
        ]);
    }

    public function update(Request $request, $id)
    {
        $auctions = Auction::where('id', $id)->first();

        $request['officer_id'] = Auth::user()->name;

        $auctions->update($request->all());

        return redirect(route('officer.auction-request'))->with('status', 'Status permintaan lelang berhasil diperbarui!');
    }
}

resources/views/admin/auctions/create.blade.php
@extends('layouts.admin-master')

@section('title', 'Lelang Baru')

@section('title-header', 'Lelang Baru')

@section('content')
<div class="row">
    <div class="col-12">
        @if (session('status'))
        <div class="alert alert-primary">
            {{ session('status') }}
        </div>
        @endif
        <div class="card">
            <form action="{{ route('admin.auctions.store') }}" method="post">
                @csrf
                <div class="card-body">

                    <div class="row">
                        <div class="form-group col">
                            <label for="goods">Barang</label>
                            <select name="goods_id" id="goods" class="form-control @error('goods_id') is-invalid @enderror">
                                <option value="">-- Pilih Barang --</option>
                                @foreach ($goodies as $goods)
                                    @if (old('goods_id') == $goods->id)
                                        <option value="{{ $goods->id }}" selected>{{ $goods->goods }}</option>
                                    @else 
                                        <option value="{{ $goods->id }}">{{ $goods->goods }}</option>
                                    @endif
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                @error('goods_id') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="start_date">Tanggal Mulai</label>
                            <input type="date" id="start_date" value="{{ old('start_date'), date('Y-m-d') }}" name="start_date" class="form-control @error('start_date') is-invalid @enderror">
                            <div class="invalid-feedback">
                                @error('start_date') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="end_date">Tanggal Selesai</label>
                            <input type="date" id="end_date" value="{{ old('end_date'), date('Y-m-d') }}" name="end_date" class="form-control @error('end_date') is-invalid @enderror">
                            <div class="invalid-feedback">
                                @error('end_date') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    {{-- <div class="row">
                        <div class="form-group col">
                            <label for="final_price">Harga Akhir</label>
                            <input type="text" id="final_price" value="{{ old('final_price') }}" name="final_price" class="form-control @error('final_price') is-invalid @enderror" placeholder="Rp. 000.000">
                            <div class="invalid-feedback">
                                @error('final_price')
                                    {{ $message }}
                                @enderror
                            </div>
                        </div>
                    </div> --}}

                    <div class="form-group row mb-4 float-right">
                        <div class="col-sm-12 col-md-7 float-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rupiah = document.getElementById('final_price');
    rupiah.addEventListener('keyup', function(e){
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    function formatRupiah(angka, prefix){
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
        split   		  = number_string.split(','),
        sisa     		  = split[0].length % 3,
        rupiah     		  = split[0].substr(0, sisa),
        ribuan     		  = split[0].substr(sisa).match(/\d{3}/gi);

        if(ribuan){
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
</script>
@endsection

resources/views/admin/auctions/export.blade.php
<!DOCTYPE html>
<html>
<head>
    {{-- Required meta tags --}}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{{ config('app.name') }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
</head>
<body>
	<center>
		<h5>Laporan Lelang</h4>
	</center>

    <br>

	<table class='table table-bordered table-striped'>
		<thead>
			<tr>
				<th style="text-align:center">No</th>
                <th>Pengguna</th>
				<th>Nama Barang</th>
				<th>Harga Akhir</th>
				<th>Tanggal Mulai</th>
				<th>Tanggal Berakhir</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			@foreach($auctions as $auction)
			<tr>
				<td style="text-align:center">{{ $loop->iteration }}</td>
				<td>{{ $auction->user->name }}</td>
				<td>{{ $auction->goods->goods }}</td>
				<td>Rp. {{ $auction->final_price }}</td>
				<td>{{ $auction->start_date }}</td>
				<td>{{ $auction->end_date }}</td>
                <td>@if ($auction['status'] == 'opened') <div class="badge badge-success">{{ auction_status($auction['status']) }}</div> @else <div class="badge badge-warning">{{ auction_status($auction['status']) }}</div> @endif</td>
			</tr>
			@endforeach
		</tbody>
	</table>

</body>
</html>

resources/views/admin/auctions/index.blade.php
@extends('layouts.admin-master')

@section('title', '| Admin Lelang')

@section('title-header', 'Lelang')

@section('content')
<div class="row">
    <div class="col-md-12">
        @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
        @endif
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h4>Lelang <span>({{ $auctions->count() }})</span></h4>
        <div class="card-header-action">
            <a href="{{ route('admin.export') }}" target="_blank" class="btn btn-danger">Ekpor <i class="fas fa-file-export"></i></a>
        </div>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-striped">
                <tbody>
                    <th scope="col">Nama Barang</th>
                    <th scope="col">Harga Akhir</th>
                    <th scope="col">Tanggal Mulai</th>
                    <th scope="col">Tanggal Berakhir</th>
                    <th scope="col">Status</th>
                    <th scope="col">Aksi</th>
                    @foreach ($auctions as $auction)
                    <tr>
                        <td>{{ $auction->goods->goods }}</td>
                        <td>Rp. {{ $auction['final_price'] }}</td>
                        <td>{{ $auction['start_date'] }}</td>
                        <td>{{ $auction['end_date'] }}</td>
                        <td>@if ($auction['status'] == 'opened') <div class="badge badge-success">{{ auction_status($auction['status']) }}</div> @else <div class="badge badge-warning">{{ auction_status($auction['status']) }}</div> @endif</td>
                        <td>
                            <a href="{{ url('/admin/auctions/') . '/' . $auction['id'] }}" class="btn btn-info"><i class="fa fa-search"></i></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer text-right">
        <nav class="d-inline-block">
            <ul class="pagination mb-0">
                {{ $auctions->links() }}
            </ul>
        </nav>
    </div>
</div>

<script>
    function deleteConfirmation(id) {
    swal({
        title: "Hapus Pengguna?",
        text: "Harap pastikan dan konfirmasi!",
        type: "warning",
        showCancelButton: !0,
        confirmButtonText: "Ya, hapus!",
        cancelButtonText: "Tidak, jangan!",
        reverseButtons: !0
    }).then(function (e) {
        if (e.value === true) {
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            $.ajax({
                type: 'DELETE',
                url: "{{url('/admin/auctions/')}}/" + id,
                data: {
                    _token: CSRF_TOKEN
                },
                dataType: 'JSON',
                success: function (results) {
                    if (results.success === true) {
                        swal("Berhasil!", results.message, "success");
                    } else {
                        swal("Gagal!", results.message, "error");
                    }
                }
            });
        } else {
            e.dismiss;
        }
    }, function (dismiss) {
        return false;
    })
}
</script>

@endsection

resources/views/admin/auctions/show.blade.php
@extends('layouts.admin-master')

@section('title', '| Detail Lelang')

@section('title-header', 'Detail Lelang')

@section('content')
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
<div class="row mt-sm-4">
    <div class="col-12 col-md-12 col-lg-6">
        <div class="card">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th scope="col">Foto</th>
                            <td><img src="{{ asset('goodsFile/' . $model->goods->photo) }}" style="max-width:100%; height:auto;"></td>
                        </tr>
                        <tr>
                            <th scope="col">Nama Barang</th>
                            <td>{{ $model->goods->goods }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Harga Akhir</th>
                            <td>Rp. {{ $model->final_price }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Desktripsi</th>
                            <td>{{ $model->goods->description }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Petugas</th>
                            <td>{{ $model->officer }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Dibuat</th>
                            <td>{{ $model->created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Diperbarui</th>
                            <td>{{ $model->created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="col">Status</th>
                            <td>@if ($model['status'] == 'opened') <div class="badge badge-success">{{ auction_status($model['status']) }}</div> @else <div class="badge badge-warning">{{ auction_status($model['status']) }}</div> @endif</td>
                        </tr>
                        <tr>
                            <th scope="col"></th>
                            <td><a href="#" class="btn btn-danger" onclick="deleteConfirmation({{ $model['id'] }})">Hapus</a></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-12 col-lg-6">
        <div class="card">
            <form action="{{ '/admin/auctions/' . $model->id }}" method="post" enctype="multipart/form-data">
                @method('patch')
                @csrf
                <div class="card-body">

                    <div class="row">
                        <div class="form-group col">
                            <label for="start_date">Tanggal Mulai</label>
                            <input type="date" name="start_date" id="start_date" class="form-control @error('start_date') is-invalid @enderror" value="{{ $model->start_date, date('Y-m-d') }}">
                            <div class="invalid-feddback">
                                @error('start_date') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="end_date">Tanggal Selesai</label>
                            <input type="date" name="end_date" id="end_date" class="form-control @error('end_date') is-invalid @enderror" value="{{ $model->end_date, date('Y-m-d') }}">
                            <div class="invalid-feddback">
                                @error('end_date') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="status">Status</label>
                            <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                @foreach ($status as $item)
                                    @if ($model->status == $item)
                                        <option value="{{ $item }}" selected>{{ auction_status($item) }}</option>
                                    @else
                                        <option value="{{ $item }}">{{ auction_status($item) }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4 float-right">
                        <div class="col-sm-12 col-md-7 float-right">
                            <button class="btn btn-primary">Perbarui</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rupiah = document.getElementById('initial_price');
    rupiah.addEventListener('keyup', function(e){
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    function formatRupiah(angka, prefix){
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
        split   		  = number_string.split(','),
        sisa     		  = split[0].length % 3,
        rupiah     		  = split[0].substr(0, sisa),
        ribuan     		  = split[0].substr(sisa).match(/\d{3}/gi);

        if(ribuan){
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }

    function deleteConfirmation(id) {
    swal({
        title: "Hapus Pengguna?",
        text: "Harap pastikan dan konfirmasi!",
        type: "warning",
        showCancelButton: !0,
        confirmButtonText: "Ya, hapus!",
        cancelButtonText: "Tidak, jangan!",
        reverseButtons: !0
    }).then(function (e) {
        if (e.value === true) {
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            $.ajax({
                type: 'DELETE',
                url: "{{url('/admin/goodies/')}}/" + id,
                data: {
                    _token: CSRF_TOKEN
                },
                dataType: 'JSON',
                success: function (results) {
                    if (results.success === true) {
                        swal("Berhasil!", results.message, "success");
                    } else {
                        swal("Gagal!", results.message, "error");
                    }
                }
            });
        } else {
            e.dismiss;
        }
    }, function (dismiss) {
        return false;
    })
}
</script>
@endsection