routes/web.php
<?php

// public
use App\Http\Controllers\PublicController;

// user
use App\Http\Controllers\User\AuctionController as User_AuctionController;

// officer
use App\Http\Controllers\Officer\AuctionController as Officer_AuctionController;
use App\Http\Controllers\Officer\OfficerController as Officer_OfficerController;

// admin
use App\Http\Controllers\Admin\AuctionController as Admin_AuctionController;
use App\Http\Controllers\Admin\OfficerController as Admin_OfficerController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Public
// Route::get('/', function () {
//     return redirect(route('index-dcms'));
// });
Route::get('/', [PublicController::class, 'index'])->name('landing-page');
Route::get('/about', [PublicController::class, 'about'])->name('about');
Route::get('/auction', [PublicController::class, 'auction'])->name('auction');
Route::get('/contact', [PublicController::class, 'contact'])->name('contact');
Route::get('/term-of-use', [PublicController::class, 'term_of_use'])->name('term-of-use');
Route::get('/privacy-policy', [PublicController::class, 'privacy_policy'])->name('privacy-policy');

// Auth User
Auth::routes(['verify' => true]);

// OAuth Google
Route::get('/google', 'User\GoogleController@redirect');
Route::get('/callback', 'User\GoogleController@callback');

// Auth Officer
Route::name('officer.')->prefix('officer')->middleware('guest')->group(function () {
    Route::get('/login', 'Auth\OfficerLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\OfficerLoginController@login');
    Route::post('/logout', 'Auth\OfficerLoginController@logout')->name('logout');
});

// Officer
Route::name('officer.')->prefix('officer')->middleware('auth:officer', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'Officer\OfficerController@index')->name('dashboard');
    // Lelang
    Route::get('/auction-request', 'Officer\AuctionController@index')->name('auction-request');
    Route::get('/auction-request/{id}', 'Officer\AuctionController@show')->name('auction-request.detail');
    Route::patch('/auction-request/{id}', 'Officer\AuctionController@update')->name('auction-request.update');
    // Profile
    Route::get('/profile', 'Officer\OfficerController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Officer\OfficerController@profile_update');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth:officer', 'verified')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
    // Officer
    Route::resource('officers', 'Admin\OfficerController', ['names' => ['index' => 'officers']]);
    // User
    Route::resource('users', 'Admin\UserController', ['names' => ['index' => 'users']]);
    // Lelang
    Route::resource('auctions', 'Admin\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::get('/export/auctions', 'Admin\AuctionController@export')->name('export');
    // Profile
    Route::get('/profile', 'Admin\AdminController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Admin\AdminController@profile_update');
});

// User
// Route::get('/user', function () {
//     return redirect(route('user.dashboard'));
// });
Route::get('/user', 'User\UserController@index');

// User
Route::name('user.')->prefix('user')->middleware('auth', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'User\UserController@index')->name('dashboard');
    // Trashed
    Route::get('/trashed', 'User\UserController@trash')->name('trashed');
    Route::get('/restore/{id}', 'User\UserController@restore')->name('restore');
    // Profile
    Route::get('/profile', 'User\UserController@profile')->name('profile');
    Route::patch('/profile/{id}', 'User\UserController@profile_update');
    // Goodies
    Route::post('/dependent-dropdown/goodies/city', 'User\GoodsController@city')->name('goodies.city');
    Route::post('/dependent-dropdown/goodies/district', 'User\GoodsController@district')->name('goodies.district');
    Route::post('/dependent-dropdown/goodies/village', 'User\GoodsController@village')->name('goodies.village');
    Route::get('/goodies/export', 'User\GoodsController@export')->name('goodies.export');
    Route::post('/goodies/export-filter', 'User\GoodsController@export_filter')->name('goodies.export_filter');
    Route::resource('goodies', 'User\GoodsController', ['names' => ['index' => 'goodies']]);
    // Auctions
    Route::get('/auctions/export', 'User\AuctionController@export')->name('auctions.export');
    Route::post('/auctions/export-filter', 'User\AuctionController@export_filter')->name('auctions.export_filter');
    Route::get('/my-auctions', 'User\AuctionController@my_auction')->name('my-auctions');
    Route::get('/auctions/{id}/detail', 'User\AuctionController@auction_detail')->name('auction-detail');
    Route::post('/auctions/{id}/follow', 'User\AuctionController@auction_follow')->name('auction-follow');
    Route::resource('auctions', 'User\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::patch('/auctions/{id}/bid', 'User\AuctionController@bid')->name('auction-bid');
    // Auction Requirement
    Route::get('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card')->name('identity-card');
    Route::patch('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card_update');
    Route::post('/dependent-dropdown/city', 'AuctionRequirementController@city')->name('city');
    Route::post('/dependent-dropdown/district', 'AuctionRequirementController@district')->name('district');
    Route::post('/dependent-dropdown/village', 'AuctionRequirementController@village')->name('village');
    Route::get('/auction-requirement/npwp', 'AuctionRequirementController@npwp')->name('npwp');
    Route::get('/auction-requirement/bank-account', 'AuctionRequirementController@bank_account')->name('bank');
    // Auctions History
    Route::get('/auction-histories/export', 'User\AuctionHistoryController@export')->name('auction-histories.export');
    Route::post('/auction-histories/export-filter', 'User\AuctionHistoryController@export_filter')->name('auction-histories.export_filter');
    Route::resource('/auction-histories', 'User\AuctionHistoryController', ['names' => ['index' => 'auction-histories']]);
    Route::patch('/auction-histories/{id}', 'User\AuctionHistoryController@update')->name('bid');
});

// log viewer
Route::get('/log', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Identity_card;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'     => 'required|string|max:255',
            'email'    => 'required|unique:users|email|string|max:255',
            'password' => 'required|min:8|confirmed|string'
        ]);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $data['password'] = Hash::make($request['password']);

        User::create($data);

        return redirect(route('admin.users.create'))->with('status', 'Pengguna berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', [
            'model' => $user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', [
            'model' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'     => 'required|string|max:255',
            'email'    => 'required|email|string|max:255',
            'password' => 'required|min:8|confirmed|string'
        ]);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $data['password'] = Hash::make($request['password']);

        $user->update($data);

        return redirect(route('admin.users'))->with('status', 'Data pengguna berhasil diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::where('id', $id)->delete();
        Identity_card::where('user_id', $id)->delete();

        return redirect(route('admin.users'))->with('status', 'Pengguna berhasil dihapus!');
    }
}

app/Http/Controllers/User/AuctionController.php
<?php

namespace App\Http\Controllers\User;

// use PDF;
use Barryvdh\DomPDF\Facade as PDF;
use App\Goods;
use App\Auction;
use Ramsey\Uuid\Uuid;
use App\Identity_card;
use App\AuctionHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class AuctionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $auctions = Auction::where('status', 'opened')->get();

        return view('users.auctions.index', compact('auctions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $goodies = Goods::where('user_id', Auth::user()->id)->whereNotIn('id', Auction::get('goods_id'))->get();

        return view('users.auctions.create', [
            'goodies'  => $goodies
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'goods_id'    => 'required|unique:auctions',
            'start_date'  => 'required|date',
            'end_date'    => 'required|date'
        ]);

        if ($request->start_date > $request->end_date) {
            return redirect(route('user.auctions.create'))->with('error', 'Pastikan Anda tidak keliru mengenai tanggal!');
        }

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $goodies = Goods::where('id', $data['goods_id'])->get();

        foreach ($goodies as $goods) {
            $initial_price = $goods->initial_price;
        }

        $data['final_price'] = str_replace("Rp. ", "", $initial_price);
        $data['user_id']     = Auth::user()->id;
        $data['status']      = 'process';

        Auction::create($data);

        return redirect(route('user.auctions.create'))->with('status', 'Permohonan Lelang berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function show(Auction $auction)
    {
        return view('users.auctions.show', [
            'model'  => $auction
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Auction $auction)
    {
        $request->validate([
            'start_date' => 'required|date',
            'end_date'   => 'required|date',
        ]);

        if ($request->start_date > $request->end_date) {
            return redirect('/user/auctions/' . $auction->id)->with('error', 'Pastikan Anda tidak keliru mengenai tanggal!');
        }

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $auction->update($data);

        return redirect('/user/auctions/' . $auction->id)->with('status', 'Lelang berhasil diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Auction  $auction
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Auction::where('id', $id)->delete();
        AuctionHistory::where('auction_id', $id)->delete();

        return redirect('/user/my-auctions')->with('status', 'Lelang berhasil dihapus!');
    }

    public function my_auction()
    {
        $auctions = Auction::where('user_id', Auth::user()->id)->paginate(10);

        return view('users.auctions.my-auction', compact('auctions'));
    }

    public function auction_detail($id)
    {
        // Mengambil data Lelang berdasarkan Lelang yang dipilih
        $auction = Auction::where('id', $id)->first();

        // Mengambil data Auction History berdasarkan barang yang dipilih dan id user yang sedang login
        $auction_history = AuctionHistory::where([
            ['user_id', '=', Auth::user()->id],
            ['goods_id', '=', $auction['goods_id']]
        ])->first();

        if ($auction_history) {
            $auction_history = AuctionHistory::where('goods_id', $auction['goods_id'])->orderBy('bid', 'DESC')->get();

            return view('users.auctions.detail', [
                'model'           => $auction,
                'auction_history' => $auction_history
            ]);
        }

        if ($auction->user_id == Auth::user()->id) {
            return redirect('user/auctions/' . $id);
        }

        return view('users.auctions.follow', [
            'model' => $auction
        ]);
    }

    public function auction_follow($id)
    {
        // Mengambil data Lelang berdasarkan Barang Lelang yang diikuti
        $auction       = Auction::where('id', $id)->first();
        // Mengambil data KTP berdasarkan id user yang login saat ini
        $identity_card = Identity_card::where('user_id', Auth::user()->id)->first();

        // Jika tidak ada data KTP user
        if (!$identity_card == Auth::user()->id) {
            // Kembalikan ke halaman detail Lelang dengan pesan
            return redirect('/user/auctions/' . $id . '/detail')->with('error', 'Untuk mengikuti lelang, pastikan Anda melengkapi KTP terlebih dahulu!');
        }

        $auction_history = AuctionHistory::where('goods_id', $auction['goods_id'])->get();

        // Jika user belum mengikuti Lelang
        if (!AuctionHistory::where([['user_id', Auth::user()->id], ['auction_id', $id]])->first()) {

            // Menambahkan data pada table auction history
            $auctionFollow = [
                'id'         => Uuid::uuid4()->getHex(),
                'auction_id' => $auction->id,
                'goods_id'   => $auction->goods_id,
                'user_id'    => Auth::user()->id,
                'bid'        => $auction->final_price
            ];

            AuctionHistory::create($auctionFollow);
        }

        // Kembalikan ke tampilan detail dengan status
        return view('users.auctions.detail', [
            'model'           => $auction,
            'auction_history' => $auction_history
        ])->with('status', 'Lelang berhasil diikuti!');
    }

    public function bid($id, Request $request)
    {
        $request->validate([
            'bid' => 'required'
        ]);

        $auction_history = AuctionHistory::where('user_id', Auth::user()->id)->first();

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        $data['bid'] = str_replace("Rp. ", "", $request->bid);

        if ($data['bid'] <= $auction_history->auction->final_price) {
            return redirect('/user/auctions/' . $id . '/detail')->with('error', 'Penawaran harus lebih besar dari harga terakhir!');
        }

        // update data dengan user sama tapi beda barang(lelang)
        AuctionHistory::where([['user_id', Auth::user()->id], ['auction_id', $id]])->update(['bid' => $data['bid']]);

        // update data final_price
        Auction::where('id', $id)->update(['final_price' => $data['bid']]);

        return $this->auction_follow($id);
    }

    public function export_filter(Request $request)
    {
        $request->validate([
            'start_export' => 'required|date',
            'end_export'   => 'required|date'
        ]);

        $auctions = Auction::where('user_id', Auth::user()->id)->whereBetween('created_at', [$request->start_export, $request->end_export])->get();

        return $this->export($auctions);
    }

    public function export($auctions)
    {
        $pdf = PDF::loadview('users.auctions.export', compact('auctions'))->setPaper('A4', 'potrait');
        return $pdf->stream('Laporan-lelang');
    }
}

resources/views/users/goodies/create.blade.php
@extends('layouts.user-master')

@section('title', '| Barang Baru')

@section('title-header', 'Barang Baru')

@section('content')
<div class="row">
    <div class="col-12">
        @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
        @endif
        <div class="card">
            <form action="{{ route('user.goodies.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card-body">

                    <div class="row">
                        <div class="form-group col">
                            <label for="photo">Foto</label>
                            <input type="file" name="photo" id="photo" class="form-control @error('photo') is-invalid @enderror">
                            <div class="invalid-feedback">
                                @error('photo') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="goods">Nama Barang</label>
                            <input type="text" id="goods" value="{{ old('goods') }}" name="goods" class="form-control @error('goods') is-invalid @enderror" placeholder="Nama Barang" autofocus>
                            <div class="invalid-feedback">
                                @error('goods') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="initial_price">Harga Awal</label>
                            <input type="text" id="initial_price" value="{{ old('initial_price') }}" name="initial_price" class="form-control @error('initial_price') is-invalid @enderror" placeholder="Rp. 000.000">
                            <div class="invalid-feedback">
                                @error('initial_price')
                                    {{ $message }}
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="description">Deskripsi Barang</label>
                            <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror" placeholder="Deskripsi Barang">{{ old('description') }}</textarea>
                            <div class="invalid-feedback">
                                @error('description') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <label class="text-danger">Lokasi Barang *</label>
                    <div class="row">
                        <div class="form-group col-6">
                            <label for="province">Provinsi</label>
                            <select name="province" id="province" class="form-control @error('province') is-invalid @enderror">
                                <option value="">-- Pilih Provinsi --</option>
                                @foreach ($provinces as $id => $name)
                                    <option value="{{ $id }}">{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-6">
                            <label for="city">Kota / Kabupaten</label>
                            <select name="city" id="city" class="form-control @error('city') is-invalid @enderror">
                                <option value="">-- Pilih Kabupaten --</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-6">
                            <label for="district">Kecamatan</label>
                            <select name="district" id="district" class="form-control @error('district') is-invalid @enderror">
                                <option value="">-- Pilih Kecamatan --</option>
                            </select>
                        </div>
                        <div class="form-group col-6">
                            <label for="village">Desa</label>
                            <select name="village" id="village" class="form-control @error('village') is-invalid @enderror">
                                <option value="">-- Pilih Desa --</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4 float-right">
                        <div class="col-sm-12 col-md-7 float-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript">
    $(function () {
        $('#province').on('change', function () {
            axios.post('{{ route('user.goodies.city') }}', {id: $(this).val()})
                .then(function (response) {
                    $('#city').empty();

                    $.each(response.data, function (id, name) {
                        $('#city').append(new Option(name, id))
                    })
                });
        });
    });

    $(function () {
        $('#city').on('change', function () {
            axios.post('{{ route('user.goodies.district') }}', {id: $(this).val()})
                .then(function (response) {
                    $('#district').empty();

                    $.each(response.data, function (id, name) {
                        $('#district').append(new Option(name, id))
                    })
                });
        });
    });

    $(function () {
        $('#district').on('change', function () {
            axios.post('{{ route('user.goodies.village') }}', {id: $(this).val()})
                .then(function (response) {
                    $('#village').empty();

                    $.each(response.data, function (name, name) {
                        $('#village').append(new Option(name, name))
                    })
                });
        });
    });

    var rupiah = document.getElementById('initial_price');

    rupiah.addEventListener('keyup', function(e) {
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    function formatRupiah(angka, prefix) {
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
        split   		  = number_string.split(','),
        sisa     		  = split[0].length % 3,
        rupiah     		  = split[0].substr(0, sisa),
        ribuan     		  = split[0].substr(sisa).match(/\d{3}/gi);

        if(ribuan) {
            separator = sisa ? '.' : '';
            rupiah    += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
</script>
@endpush

resources/views/users/goodies/export.blade.php
<!DOCTYPE html>
<html>
	<head>
        {{-- Required meta tags --}}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{{ config('app.name') }}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<style type="text/css">
			table tr td,
			table tr th{
				font-size: 9pt;
			}
		</style>
	</head>
	<body>
	<center>
		{{-- <img src="{{ asset('img/favicon.png') }}" width="50" alt="logo"> --}}
		<h5>Laporan Barang</h5>
	</center>

	<br>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th style="text-align:center">No</th>
				<th>Barang</th>
				<th>Deskripsi</th>
				<th>Dibuat</th>
				<th>Harga Awal</th>
			</tr>
		</thead>
		<tbody>
			@foreach($goodies as $goods)
			<tr>
				<td style="text-align:center">{{ $loop->iteration }}</td>
				<td>{{ $goods->goods }}</td>
				<td>{{ $goods->description }}</td>
				<td>{{ $goods->created_at }}</td>
				<td>Rp. {{ $goods->initial_price }}</td>
			</tr>
			@endforeach
		</tbody>
	</table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>

resources/views/users/goodies/index.blade.php
@extends('layouts.user-master')

@section('title', '| Barang')

@section('title-header', 'Barang')

@section('content')
<div class="row">
    <div class="col-md-12">
        @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
        @endif
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h4>Barang <span>({{ $goodies->count() }})</span></h4>
        <div class="card-header-action">
            <button class="btn btn-danger" id="modal-4">Ekspor <i class="fas fa-file-export"></i></button>
        </div>
    </div>

    <!-- Export Modal -->
    <form class="modal-part" id="modal-cetak" target="_blank" action="{{ route('user.goodies.export_filter') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="start_export">Dari</label>
            <div class="input-group">
                <input type="date" name="start_export" id="start_export" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="end_export">Sampai</label>
            <div class="input-group">
                <input type="date" name="end_export" id="end_export" class="form-control">
            </div>
        </div>
        <div class="form-group row mb-4 float-right">
            <div class="col-sm-12 col-md-7 float-right">
                <button class="btn btn-primary">Cetak</button>
            </div>
        </div>
    </form>

    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-striped">
                <tbody>
                    <th scope="col">Nama Barang</th>
                    <th scope="col">Harga Awal</th>
                    <th scope="col">Lokasi</th>
                    <th scope="col">Tanggal Dibuat</th>
                    <th scope="col"></th>
                    @foreach ($goodies as $goods)
                    <tr>
                        <td>{{ $goods['goods'] }}</td>
                        <td>Rp. {{ $goods['initial_price'] }}</td>
                        <td>{{ $goods['village'] }}</td>
                        <td>{{ $goods['created_at'] }}</td>
                        <td class="text-right">
                            <a href="{{ '/user/goodies/' . $goods['id'] }}" class="btn btn-info"><i class="fa fa-search"></i></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer text-right">
        <nav class="d-inline-block">
            <ul class="pagination mb-0">
                {{ $goodies->links() }}
            </ul>
        </nav>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('stisla/assets/js/page/bootstrap-modal.js') }}"></script>
@endpush