routes/web.php
<?php

// public
use App\Http\Controllers\PublicController;

// user
use App\Http\Controllers\User\AuctionController as User_AuctionController;

// officer
use App\Http\Controllers\Officer\AuctionController as Officer_AuctionController;
use App\Http\Controllers\Officer\OfficerController as Officer_OfficerController;

// admin
use App\Http\Controllers\Admin\AuctionController as Admin_AuctionController;
use App\Http\Controllers\Admin\OfficerController as Admin_OfficerController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Public
// Route::get('/', function () {
//     return redirect(route('index-dcms'));
// });
Route::get('/', [PublicController::class, 'index'])->name('landing-page');
Route::get('/about', [PublicController::class, 'about'])->name('about');
Route::get('/auction', [PublicController::class, 'auction'])->name('auction');
Route::get('/contact', [PublicController::class, 'contact'])->name('contact');
Route::get('/term-of-use', [PublicController::class, 'term_of_use'])->name('term-of-use');
Route::get('/privacy-policy', [PublicController::class, 'privacy_policy'])->name('privacy-policy');

// Auth User
Auth::routes(['verify' => true]);

// OAuth Google
Route::get('/google', 'User\GoogleController@redirect');
Route::get('/callback', 'User\GoogleController@callback');

// Auth Officer
Route::name('officer.')->prefix('officer')->middleware('guest')->group(function () {
    Route::get('/login', 'Auth\OfficerLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\OfficerLoginController@login');
    Route::post('/logout', 'Auth\OfficerLoginController@logout')->name('logout');
});

// Officer
Route::name('officer.')->prefix('officer')->middleware('auth:officer', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'Officer\OfficerController@index')->name('dashboard');
    // Lelang
    Route::get('/auction-request', 'Officer\AuctionController@index')->name('auction-request');
    Route::get('/auction-request/{id}', 'Officer\AuctionController@show')->name('auction-request.detail');
    Route::patch('/auction-request/{id}', 'Officer\AuctionController@update')->name('auction-request.update');
    // Profile
    Route::get('/profile', 'Officer\OfficerController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Officer\OfficerController@profile_update');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth:officer', 'verified')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
    // Officer
    Route::resource('officers', 'Admin\OfficerController', ['names' => ['index' => 'officers']]);
    // User
    Route::resource('users', 'Admin\UserController', ['names' => ['index' => 'users']]);
    // Lelang
    Route::resource('auctions', 'Admin\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::get('/export/auctions', 'Admin\AuctionController@export')->name('export');
    // Profile
    Route::get('/profile', 'Admin\AdminController@profile')->name('profile');
    Route::patch('/profile/{id}', 'Admin\AdminController@profile_update');
});

// User
// Route::get('/user', function () {
//     return redirect(route('user.dashboard'));
// });
Route::get('/user', 'User\UserController@index');

// User
Route::name('user.')->prefix('user')->middleware('auth', 'verified')->group(function () {
    // Dashboard
    Route::get('/dashboard', 'User\UserController@index')->name('dashboard');
    // Trashed
    Route::get('/trashed', 'User\UserController@trash')->name('trashed');
    Route::get('/restore/{id}', 'User\UserController@restore')->name('restore');
    // Profile
    Route::get('/profile', 'User\UserController@profile')->name('profile');
    Route::patch('/profile/{id}', 'User\UserController@profile_update');
    // Goodies
    Route::post('/dependent-dropdown/goodies/city', 'User\GoodsController@city')->name('goodies.city');
    Route::post('/dependent-dropdown/goodies/district', 'User\GoodsController@district')->name('goodies.district');
    Route::post('/dependent-dropdown/goodies/village', 'User\GoodsController@village')->name('goodies.village');
    Route::get('/goodies/export', 'User\GoodsController@export')->name('goodies.export');
    Route::post('/goodies/export-filter', 'User\GoodsController@export_filter')->name('goodies.export_filter');
    Route::resource('goodies', 'User\GoodsController', ['names' => ['index' => 'goodies']]);
    // Auctions
    Route::get('/auctions/export', 'User\AuctionController@export')->name('auctions.export');
    Route::post('/auctions/export-filter', 'User\AuctionController@export_filter')->name('auctions.export_filter');
    Route::get('/my-auctions', 'User\AuctionController@my_auction')->name('my-auctions');
    Route::get('/auctions/{id}/detail', 'User\AuctionController@auction_detail')->name('auction-detail');
    Route::post('/auctions/{id}/follow', 'User\AuctionController@auction_follow')->name('auction-follow');
    Route::resource('auctions', 'User\AuctionController', ['names' => ['index' => 'auctions']]);
    Route::patch('/auctions/{id}/bid', 'User\AuctionController@bid')->name('auction-bid');
    // Auction Requirement
    Route::get('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card')->name('identity-card');
    Route::patch('/auction-requirement/identity-card', 'AuctionRequirementController@identity_card_update');
    Route::post('/dependent-dropdown/city', 'AuctionRequirementController@city')->name('city');
    Route::post('/dependent-dropdown/district', 'AuctionRequirementController@district')->name('district');
    Route::post('/dependent-dropdown/village', 'AuctionRequirementController@village')->name('village');
    Route::get('/auction-requirement/npwp', 'AuctionRequirementController@npwp')->name('npwp');
    Route::get('/auction-requirement/bank-account', 'AuctionRequirementController@bank_account')->name('bank');
    // Auctions History
    Route::get('/auction-histories/export', 'User\AuctionHistoryController@export')->name('auction-histories.export');
    Route::post('/auction-histories/export-filter', 'User\AuctionHistoryController@export_filter')->name('auction-histories.export_filter');
    Route::resource('/auction-histories', 'User\AuctionHistoryController', ['names' => ['index' => 'auction-histories']]);
    Route::patch('/auction-histories/{id}', 'User\AuctionHistoryController@update')->name('bid');
});

// log viewer
Route::get('/log', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);

app/Officer.php
<?php

namespace App;

use App\Level;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Officer extends Authenticatable
{
    protected $guarded = [];

    protected $hidden  = [
        'password', 'remember_token'
    ];

    public function level()
    {
        return $this->belongsTo(Level::class, 'level_id');
    }
}

app/Http/Controllers/Admin/OfficerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Officer;
use Ramsey\Uuid\Uuid;

class OfficerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $officers = Officer::all();

        return view('admin.officers.index', compact('officers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $levels = [1 => 'Administrator', 2 => 'Officer'];

        return view('admin.officers.create', compact('levels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'   => 'required|string|max:255',
            'last_name'    => 'required|string|max:255',
            'name'         => 'string|max:255',
            'level_id'     => 'required|numeric',
            'password'     => 'required|confirmed|string|min:8',
            'email'        => 'required|email|unique:officers',
            'phone_number' => 'required|numeric|min:8|unique:officers'
        ]);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        unset($data['password_confirmation']);

        $data['email_verified_at'] = now();
        $data['id'] = Uuid::uuid4()->getHex();
        $data['password'] = Hash::make($request['password']);
        $data['name']     = $data['first_name'] . ' ' . $data['last_name'];

        Officer::create($data);

        return redirect(route('admin.officers.create'))->with('status', 'Petugas berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function show(Officer $officer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function edit(Officer $officer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Officer $officer)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Officer::destroy($id);

        return redirect(route('admin.officers'))->with('status', 'Petugas berhasil dihapus!');
    }
}

app/Http/Controllers/Officer/AuctionController.php
<?php

namespace App\Http\Controllers\Officer;

use App\Auction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AuctionController extends Controller
{
    public function index()
    {
        $auctions = Auction::all();

        return view('officers.auctions.index', [
            'auctions' => $auctions
        ]);
    }

    public function show($id)
    {
        $auctions = Auction::where('id', $id)->first();
        $status   = ['process', 'opened', 'closed'];

        return view('officers.auctions.show', [
            'model' => $auctions,
            'status' => $status
        ]);
    }

    public function update(Request $request, $id)
    {
        $auctions = Auction::where('id', $id)->first();

        $request['officer_id'] = Auth::user()->name;

        $auctions->update($request->all());

        return redirect(route('officer.auction-request'))->with('status', 'Status permintaan lelang berhasil diperbarui!');
    }
}

app/Http/Controllers/Officer/OfficerController.php
<?php

namespace App\Http\Controllers\Officer;

// use File;
use App\User;
use App\Goods;
use App\Officer;
use App\Auction;
use App\AuctionHistory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class OfficerController extends Controller
{
    public function index()
    {
        $users    = User::all();
        $officers = Officer::all();
        $goodies  = Goods::all();
        $auctions = Auction::all();

        return view('officers.index', [
            'users' => $users,
            'officers' => $officers,
            'goodies' => $goodies,
            'auctions' => $auctions
        ]);
    }

    public function profile()
    {
        $goodies           = Goods::where('user_id', Auth::user()->id)->get();
        $auctions          = Auction::where('user_id', Auth::user()->id)->get();
        $auction_histories = AuctionHistory::where('user_id', Auth::user()->id)->get();

        return view('officers.profile', [
            'goodies'           => $goodies,
            'auctions'          => $auctions,
            'auction_histories' => $auction_histories
        ]);
    }

    public function profile_update(Request $request)
    {
        $request->validate([
            'avatar'       => 'mimes:jpg,png,jpeg|max:2048',
            'first_name'   => 'required|string',
            'last_name'    => 'required|string',
            'email'        => 'required|email',
            'phone_number' => 'required|numeric',
            'description'  => 'required'
        ]);

        $officer = Officer::find(Auth::user()->id);

        $data = [];
        foreach ($request->all() as $key => $value) {
            $data[$key] = $value;
        }

        if (!$request->avatar) {
            $data['avatar'] = $officer->avatar;
        } else {
            $data['avatar'] = $request->avatar;
            $data['avatar'] = time() . '_' . Auth::user()->name . '.' . $request->file('avatar')->extension();
            $request->file('avatar')->move(public_path('usersFile'), $data['avatar']);
        }

        Storage::delete('usersFile/' . $officer->avatar);
        $officer->update($data);

        return redirect('/officer/profile/')->with('status', 'Profil berhasil diperbarui!');
    }
}

resources/views/admin/officers/create.blade.php
@extends('layouts.admin-master')

@section('title', 'Petugas Baru')

@section('title-header', 'Petugas Baru')

@section('content')
<div class="row">
    <div class="col-12">
        @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
        @endif
        <div class="card">
            <form action="{{ route('admin.officers.store') }}" method="post">
                @csrf
                <div class="card-body">

                    <div class="row">
                        <div class="form-group col-6">
                            <label for="first_name">Nama Depan</label>
                            <input type="text" id="first_name" value="{{ old('first_name') }}" name="first_name" class="form-control @error('first_name') is-invalid @enderror" placeholder="Nama Depan" autofocus>
                            <div class="invalid-feedback">
                                @error('first_name') {{ $message }} @enderror
                            </div>
                        </div>
                        <div class="form-group col-6">
                            <label for="last_name">Nama Belakang</label>
                            <input type="text" id="last_name" value="{{ old('last_name') }}" name="last_name" class="form-control @error('last_name') is-invalid @enderror" placeholder="Nama Belakang" autofocus>
                            <div class="invalid-feedback">
                                @error('last_name') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="email">Surel</label>
                            <input type="text" id="email" name="email" value="{{ old('email') }}" class="form-control @error('email') is-invalid @enderror" placeholder="surel@contoh.com">
                            <div class="invalid-feedback">
                                @error('email') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="phone_number">No. Telepon</label>
                            <input type="text" id="phone_number" name="phone_number" value="{{ old('phone_number') }}" class="form-control @error('phone_number') is-invalid @enderror" placeholder="Minimal 8-14 Angka">
                            <div class="invalid-feedback">
                                @error('phone_number') {{ $message }} @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col">
                            <label for="level">Wewenang</label>
                            <select name="level_id" id="level" class="form-control">
                                <option value="" selected>-- Pilih Wewenang --</option>
                                @foreach ($levels as $key => $level)
                                    @if (old('level_id') == $key)
                                        <option value="{{ $key }}" selected>{{ translation_level($level) }}</option>
                                    @else
                                        <option value="{{ $key }}">{{ translation_level($level) }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-6">
                            <label for="password">Kata Sandi</label>
                            <input type="password" name="password" id="password" class="form-control @error('password') is-invalid @enderror" placeholder="Minimal 8 karakter & berisi alfanumerik" autocomplete="new-password">
                            <div class="invalid-feedback">
                                @error('password') {{ $message }} @enderror
                            </div>
                        </div>

                        <div class="form-group col-6">
                            <label for="password2">Konfirmasi Kata Sandi</label>
                            <input type="password" name="password_confirmation" id="password2" class="form-control @error('password') is-invalid @enderror" placeholder="Minimal 8 karakter & berisi alfanumerik" autocomplete="new-password">
                            <div class="invalid-feedback">
                                @error('password') {{ $message }} @enderror
                            </div>
                        </div>

                    </div>

                    <div class="form-group row mb-4 float-right">
                        <div class="col-sm-12 col-md-7 float-right">
                            <button class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/officers/index.blade.php
@extends('layouts.admin-master')

@section('title', 'Petugas')

@section('title-header', 'Petugas')

@section('content')
<div class="row">
    <div class="col-md-12">
        @if (session('status'))
        <div class="alert alert-primary">
            {{ session('status') }}
        </div>
        @endif
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h4>Petugas <span>({{ $officers->count() }})</span></h4>
        {{-- <div class="card-header-action">
            <a href="{{ route('admin.officers.create') }}" class="btn btn-danger">Ekspor <i class="fas fa-file-export"></i></a>
        </div> --}}
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-striped">
                <tbody>
                    <th scope="col">Nama</th>
                    <th scope="col">Surel</th>
                    <th scope="col">Wewenang</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                    @foreach ($officers as $officer)      
                    <tr>
                        <td>{{ $officer['name'] }}</td>
                        <td>{{ $officer['email'] }}</td>
                        <td>{{ officer_level($officer->level_id) }}</td>
                        <td>@if ($officer['email_verified_at']) <div class="badge badge-success">Aktif</div> @else <div class="badge badge-danger">Belum Aktif</div> @endif</td>
                        <td class="text-right">
                            <form action="{{ '/admin/officers/' . $officer->id }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger @if($officer->id == Auth::user()->id) d-none @endif"><i class="fa fa-trash"></i></button>
                                <a href="{{ '/admin/officers/' . $officer['id'] . '/edit' }}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                <a href="{{ '/admin/officers/' . $officer['id'] }}" class="btn btn-info"><i class="fa fa-search"></i></a>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer text-right">
        <nav class="d-inline-block">
            <ul class="pagination mb-0">
                {{-- {{ $officers->links() }} --}}
            </ul>
        </nav>
    </div>
</div>

<script>
    function deleteConfirmation(id) {
    swal({
        title: "Hapus Pengguna?",
        text: "Harap pastikan dan konfirmasi!",
        type: "warning",
        showCancelButton: !0,
        confirmButtonText: "Ya, hapus!",
        cancelButtonText: "Tidak, jangan!",
        reverseButtons: !0
    }).then(function (e) {
        if (e.value === true) {
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            $.ajax({
                type: 'DELETE',
                url: "{{url('/admin/officers/')}}/" + id,
                data: {
                    _token: CSRF_TOKEN
                },
                dataType: 'JSON',
                success: function (results) {
                    if (results.success === true) {
                        swal("Berhasil!", results.message, "success");
                    } else {
                        swal("Gagal!", results.message, "error");
                    }
                }
            });
        } else {
            e.dismiss;
        }
    }, function (dismiss) {
        return false;
    })
}
</script>

@endsection